const SIZE=15, canvas=document.getElementById('board'), ctx=canvas.getContext('2d');
let board=Array.from({length:SIZE},()=>Array(SIZE).fill(0)), current=1, history=[], winner=0, mode='pvp', scores=[0,0];
function resize(){const d=window.devicePixelRatio||1, r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()} window.addEventListener('resize',resize);
function draw(){const w=canvas.clientWidth, pad=w*.035, gap=(w-pad*2)/(SIZE-1);ctx.clearRect(0,0,w,w);ctx.fillStyle='#d9a36a';ctx.fillRect(0,0,w,w);ctx.strokeStyle='rgba(82,48,21,.62)';ctx.lineWidth=1;for(let i=0;i<SIZE;i++){let p=pad+i*gap;ctx.beginPath();ctx.moveTo(p,pad);ctx.lineTo(p,w-pad);ctx.stroke();ctx.beginPath();ctx.moveTo(pad,p);ctx.lineTo(w-pad,p);ctx.stroke()}[3,7,11].forEach(y=>[3,7,11].forEach(x=>{ctx.fillStyle='#744b2d';ctx.beginPath();ctx.arc(pad+x*gap,pad+y*gap,3,0,Math.PI*2);ctx.fill()}));board.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;let px=pad+x*gap,py=pad+y*gap,r=gap*.42;ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.fillStyle=v===1?'#242831':'#fff';ctx.shadowColor='rgba(0,0,0,.25)';ctx.shadowBlur=5;ctx.shadowOffsetY=2;ctx.fill();ctx.shadowColor='transparent';if(v===2){ctx.strokeStyle='#d0d0d0';ctx.stroke()}}));if(history.length){const m=history[history.length-1];ctx.strokeStyle='#c76c43';ctx.lineWidth=2;ctx.strokeRect(pad+m.x*gap-5,pad+m.y*gap-5,10,10)}}
function click(e){if(winner)return;const r=canvas.getBoundingClientRect(),w=canvas.clientWidth,pad=w*.035,gap=(w-pad*2)/(SIZE-1);let x=Math.round((e.clientX-r.left-pad)/gap),y=Math.round((e.clientY-r.top-pad)/gap);if(x<0||x>=SIZE||y<0||y>=SIZE||board[y][x])return;place(x,y,current);if(mode==='ai'&&!winner&&current===2)setTimeout(aiMove,260)}
function place(x,y,p){board[y][x]=p;history.push({x,y,p});draw();update();if(check(x,y,p)){winner=p;scores[p-1]++;document.getElementById('statusTitle').textContent=(p===1?'黑方':'白方')+'获胜';toast((p===1?'黑方':'白方')+'连成五子！');update();return}current=3-p;update()}
function check(x,y,p){for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(let s=1;s<5;s++){if(board[y+dy*s]?.[x+dx*s]===p)n++;else break}for(let s=1;s<5;s++){if(board[y-dy*s]?.[x-dx*s]===p)n++;else break}if(n>=5)return true}return false}
function aiMove(){let options=[];for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++)if(!board[y][x]){let near=false;for(let yy=-2;yy<=2;yy++)for(let xx=-2;xx<=2;xx++)if(board[y+yy]?.[x+xx])near=true;if(near)options.push({x,y})}if(!options.length)options=[{x:7,y:7}];let best=options[Math.floor(Math.random()*options.length)];place(best.x,best.y,2)}
function update(){document.getElementById('moveCount').textContent='第 '+history.length+' 手';document.getElementById('historyCount').textContent=history.length;document.getElementById('blackScore').textContent=scores[0];document.getElementById('whiteScore').textContent=scores[1];document.getElementById('turnLabel').textContent=winner?'GAME OVER':(current===1?'BLACK':'WHITE');document.getElementById('turnDot').className='turn-dot '+(current===1?'black':'white');if(!winner)document.getElementById('statusTitle').textContent=current===1?'黑方回合':'白方回合';const ol=document.getElementById('history');ol.innerHTML=history.slice().reverse().map((m,i)=>`<li><span><b>${history.length-i}.</b> ${m.p===1?'黑方':'白方'}</span><span>${String.fromCharCode(65+m.x)}${m.y+1}</span></li>`).join('')}
function reset(){board=Array.from({length:SIZE},()=>Array(SIZE).fill(0));current=1;history=[];winner=0;update();draw()}function undo(){if(!history.length||winner)return;let n=mode==='ai'?2:1;while(n--&&history.length){const m=history.pop();board[m.y][m.x]=0}current=1;update();draw()}function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
canvas.addEventListener('click',click);document.getElementById('resetBtn').onclick=reset;document.getElementById('newGameBtn').onclick=reset;document.getElementById('undoBtn').onclick=undo;document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelector('.mode.active').classList.remove('active');b.classList.add('active');mode=b.dataset.mode;document.getElementById('whiteName').textContent=mode==='ai'?'COMPUTER':'PLAYER 2';reset()});requestAnimationFrame(resize);
